# Experiment configurations
platform: "moonshot"
job_id: "step_prover_debug"
max_workers: 1
verbose: true


# Dataset settings
datasets:
  - name: "AI-MO/human-statements-dataset-v2-20250118"
    split: "train"
pass_at: 1
shard_size: 1

# TODO:
# filter_threshold: 10
# add_negation: true

# Model arguments
model_params:
  model_path: 
    - "/home/mantas/models/DeepSeek-Prover-V1.5-RL"
  url:
    - "http://0.0.0.0:8081/v1"
  n_retry: 0
  temperature: 0
  max_length: 2048
  prompt_type: "text"
  tokenizer_path: "/home/mantas/models/DeepSeek-Prover-V1.5-RL"

# verifier arguments
verifier_params:
  url: "https://kimina.saas.moonshot.cn/lean4-evaluator"
  timeout: 60

# Search arguments
search_params:
  search_method: bfs
  num_sampled_tactics: 1
  max_expansions: 1
  search_timeout: 60
  step_timeout: null
  serialize_interval: 60
  resume_from_checkpoint: True


# Output directories
working_dir: "./{job_id}"
huggingface_cache_dir: "./.cache/ttmmpp"

logging_dir: "{working_dir}/log/proof_search/"
statement_dir: "{working_dir}/statements"
verified_proofs_dir: "{working_dir}/verified_proofs"
# proof_record_dir: "{working_dir}/proof_records.jsonl"

