# Dataset configuration
data_path: 'KbsdJames/Omni-MATH'
data_split: ['test']
informal_statement: 'problem'
answer: 'answer'
informal_proof: 'solution'
difficulty: 'difficulty'
domain: 'domain'

has_header: true # if false, adds a default header

# llm_config
batch_size: 32
model_path: 'ep-20250128143818-wq8s5'
sampling_config:
  n: 1
  temperature: 0.7
  max_tokens: 4096
  top_p: 0.95
  stop: ['```']



