### model
model_name_or_path: deepseek-ai/DeepSeek-Prover-V1.5-SFT

### set wandb
report_to: wandb
run_name: deepseekprover_finetune

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: config/deepspeed/ds_z3_config.json

### dataset
dataset: wholeproof-data-pt-241231
packing: false
template: default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /DATA/disk3/mert/models/DeepSeekProverV1.5_SFT_241231
logging_steps: 1000
save_steps: 21000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10000

### push to hub
push_to_hub: true
hub_private_repo: true
hub_model_id: AI-MO/DeepSeekProverV1.5_SFT_241231
hub_strategy: end