### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B

### set wandb
report_to: wandb
run_name: qwencoder_finetune

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: config/deepspeed/ds_z3_config.json

### dataset
dataset: auto-sft-moon-santa-v1beta1-pt
packing: false
template: default
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /DATA/disk3/mert/models/Qwen2.5-Base_Prover_auto-sft-moon-santa-v1beta1
logging_steps: 500
save_strategy: epoch
save_steps: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: epoch
eval_steps: 0.5

### push to hub
push_to_hub: true
hub_private_repo: true
hub_model_id: AI-MO/Qwen2.5-Base_Prover_auto-sft-moon-santa-v1beta1
hub_strategy: end