# Dataset configuration
data_path: 'AI-MO/aops-autoformalization-v0.1'
data_split: ['train']
has_header: true # if false, adds a default header
has_sorry: true # if true, removes the sorry from the end of the formal statement
formal_columns: ['autoformalization'] # columns to sum to get the formal statement
info_columns: []
additional_colunms: []
index_column: 'index'

# Verifier configuration
lean_workers: 32
lean_timeout: 60  # seconds
lean_memory_limit: 256 # MB
lean_retries: 1

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'

# Model configuration
batch_size: 32
model_path: 'deepseek-ai/DeepSeek-Prover-V1.5-RL'
sampling_config:
  n: 64
  temperature: 1
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

do_evaluate: false
store_intermediate_results: true

# below here is not implemented yet

# Generation Mode
generation:
  mode: 'FullProof' # options are FullProof

# Output
output:
  dataset_id: 'AI-MO/math-autoformalization-v0.1_DeepSeek-Prover-V1.5-RL'
  dataset_branch: 'temp1_topp095_sample1'