# Dataset configuration
data_path: 'AI-MO/minif2f_test'
data_split: ['train']
has_header: true # if false, adds a default header
has_sorry: false # if true, removes the sorry from the end of the formal statement
formal_columns: ['formal_statement'] # columns to sum to get the formal statement
info_columns: []
additional_colunms: []
index_column: 'name'

# Verifier configuration
lean_workers: 40
lean_timeout: 60  # seconds
lean_memory_limit: 32 # GB
lean_retries: 1

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'

# Model configuration
batch_size: 8
model_path: 'AI-MO/DeepSeek-Prover-V1.5-RL-PT-241211'
sampling_config:
  n: 64
  temperature: 1
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

vllm:
  tensor_parallel_size: 1

do_evaluate: true
store_intermediate_results: true