# Dataset configuration
data_path: 'AI-MO/math-autoformalization-v0.1'
data_split: ['train']
has_header: true # if false, adds a default header
has_sorry: true # if true, removes the sorry from the end of the formal statement
formal_columns: ['autoformalization'] # columns to sum to get the formal statement
info_columns: []
additional_colunms: []
index_column: 'index'

# Verifier configuration
lean_workers: 20
lean_timeout: 120  # seconds
lean_memory_limit: 32 # GB
lean_retries: 1

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'

# Model configuration
batch_size: 8
model_path: '/home/mert/models/DeepSeek-Prover-V1.5-RL-PT-241211'
sampling_config:
  n: 8
  temperature: 1
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

do_evaluate: true
store_intermediate_results: true
