# Dataset configuration
data_path: 'AI-MO/auto-statements-candidates'
data_split: ['train']
has_header: true # if false, adds a default header
has_sorry: true # if true, removes the sorry from the end of the formal statement
formal_columns: ['formal_statement'] # columns to sum to get the formal statement
info_columns: []
additional_columns: []
index_column: 'uuid'

# Verifier configuration
lean_workers: 32
lean_timeout: 60  # seconds
lean_memory_limit: 32 # GB
lean_retries: 1

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'

# Model configuration
batch_size: 64
model_path: 'deepseek-ai/DeepSeek-Prover-V1.5-RL'
sampling_config:
  n: 64
  temperature: 1.0
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

do_evaluate: false # disables lean feedback
store_intermediate_results: true