# Dataset configuration
data_path: 'KbsdJames/Omni-MATH'
data_split: ['train']
informal_statement: 'problem'
formal_statement: 'proof_input'
formal_proof: 'proof'


has_header: true # if false, adds a default header

# llm_config
batch_size: 32
model_path: 'ep-20250128143818-wq8s5'
sampling_config:
  n: 1
  temperature: 0.7
  max_tokens: 4096
  top_p: 0.95
  stop: ['```']