# TEST DATASET CONFIGURATION
data_path: 'AI-MO/minif2f_test_noinformal' # HF dataset id
data_split: ['train'] # list of splits to concatenate

has_header: true # if false, adds a default header
has_sorry: false # if true, removes the sorry from the end of the formal statement before completion

formal_columns: ['formal_statement'] # columns to sum to get the formal statement
index_column: 'name' # column to use as index

# Additional Fields (currently not used)
info_columns: []
additional_colunms: []

# -------------------------------------

# NUMBER OF PROCESSES
CUDA_VISIBLE_DEVICES: '0,1,2,3' # 4 processes using 4 GPUs
n_verification_processes: 30

# ---------------------------

# LEAN4 VERIFIER CONFIGURATION
lean_feedback: 'server' # 'server' or 'local'
lean_workers: 5 
lean_timeout: 60  # seconds

# ---------------------------

# MODEL CONFIGURATION
batch_size: 8
model_path: 'AI-MO/Qwen_Prover_V1_241227'
sampling_config:
  n: 64
  temperature: 1
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

# ---------------------------

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'