# TEST DATASET CONFIGURATION
data_path: 'AI-MO/inhouse-evaluation-v1-20250102' # HF dataset id
data_split: ['inhouse_evaluation_others_10_percent'] # list of splits to concatenate

has_header: true # if false, adds a default header
has_sorry: false # if true, removes the sorry from the end of the formal statement before completion

formal_columns: ['formal_statement'] # columns to sum to get the formal statement
index_column: 'uuid' # column to use as index

# Additional Fields (currently not used)
info_columns: []
additional_colunms: []

# -------------------------------------

# NUMBER OF PROCESSES
CUDA_VISIBLE_DEVICES: '4,5,6,7' # 4 processes using 4 GPUs
n_verification_processes: 20

# ---------------------------

# LEAN4 VERIFIER CONFIGURATION
lean_feedback: 'server' # 'server' or 'local'
lean_workers: 5 
lean_timeout: 60  # seconds

# ---------------------------

# MODEL CONFIGURATION
batch_size: 8
model_path: 'AI-MO/DeepSeekProverV1.5_RL_241231'
sampling_config:
  n: 128
  temperature: 1
  max_tokens: 2048
  top_p: 0.95
  stop: ['```']

# ---------------------------

# Prompt Template (has to have 'formal_statement')
prompt_template: 'Complete the following Lean 4 code:\n\n```lean4\n{formal_statement}'